### ISSUE TITLE
Graph of actual performance of fake DS18B20

### ISSUE THREAD

**Issue by emulti** [cpetrich/counterfeit_DS18B20#17]
Hi,

Thanks for highlighting this fake sensor issue!

Unfortunately I found out about it after I wasted my money on a bunch of waterproof "DS18B20" sensors on eBay in 2019.
The ROM codes are of the form 28-tt-tt-43-xx-00-80-crc. 

To highlight just how useless (and potentially dangerous if used in a temperature control system) these fakes are, have a look at this graph of the temperature output at 12 bits resolution from five sensors at identical temperature. There are four fakes, and one genuine item. Temperatures are being read using the standard DallasTemperature library on an Arduino.

You only get one guess which is the genuine one...

[One genuine, four fake DS18B20](https://drive.google.com/file/d/1Gf_zJCeZCzvjz2Hi7iOrXgX0H4oLWanp/view?usp=sharing)

Building a precise temperature control system is practically impossible with this garbage. The readings vary randomly by so much, and in an asymmetric way, that even by applying heavy smoothing they are neither accurate to within a degree, or stable. The response time of the smoothing loop becomes uselessly slow for many applications.

Chris

**Comment by emulti** [comment]
I should have know better, but the inside of the 'waterproof sensor' exceeded my lowest expectations.
The fake sensor (which is of course marked 'Dallas' with a plausible looking batch code) is potted in a low-grade silicone-like material that looks like bathroom sealant. 
The maker has gone to the trouble of fitting sleeves over the soldered connections, but forgot to push the sleeves up over the pins of the device. As a result, two of the pins are almost touching.
[inside 'waterproof' fake DS1820B sensor](https://drive.google.com/file/d/1nQ8Qz8uP536ujuHfQsIUE3awI94l5KW1/view?usp=sharing)
['Intelligent' sleeving- pins almost touching](https://drive.google.com/file/d/1zlkP5eCPMlDN-jtDa6Z0NHZQPwDlbJDL/view?usp=sharing)

I advise anyone looking for DS18B20 sensors not to buy them from eBay/China!

**Comment by heitorPB** [comment]
Nice plot! Would you consider adding it the the README?

**Comment by cpetrich** [comment]
@emulti Thanks for the pointer! I believe I've ordered some based on your hints and will follow up when I receive them.

@heitorPB Got to think about it. While I agree that their performance is garbage they seem to be old stock from a European distributor if I understood @emulti correctly, i.e. they perform much worse than the sensors one can expect to get from a Chinese distributor these days. Again, I'll think about it once I manage to buy some.

**Comment by emulti** [comment]
To clarify, they were bought direct from an eBay seller in China in 2019, but I didn't get round to using them until this month. 
The rubbish build quality of the sensors, slow response due to potting in low grade sealant, when the cable is such cheap rubbish that it is hard to solder- all these things on top of the useless performance mean they were a complete waste of money. We live and learn.

**Comment by cpetrich** [comment]
To follow up: the probes I received today contain Family B2 sensors.
