### ISSUE TITLE
UMW DS18B20

### ISSUE THREAD

**Issue by N-Storm** [cpetrich/counterfeit_DS18B20#2]
Hello,

I've found those chips manufactured by UMW(Youtai Semiconductor Co., Ltd.) and labeled as DS18B20. 

Found here: https://lcsc.com/product-detail/Temperature-Sensors_UMW-Youtai-Semiconductor-Co-Ltd-DS18B20_C376006.html
They also have a datasheet for these. It's in Chinese, but some information could be discovered.

Chips are marked as UMW 18B20 so they are distinguished from Dallas. But we all know how some chips could be re-marked by various fake sellers.

I don't have any of them or ordered any. But probably this information could be useful.

**Comment by cpetrich** [comment]
much appreciate the pointer!

I'd dare a prediction based on the datasheet: Family B1. How exciting!

**Comment by cpetrich** [comment]
Turns out they are Family B1 indeed.

**Comment by makerhelp** [comment]
I have bought 10 og these and they self destroy😡
