### ISSUE TITLE
Could you update the MAX31820 description?

### ISSUE THREAD

**Issue by dc-eds** [cpetrich/counterfeit_DS18B20#25]
Thanks for writing this up.  There are far too many counterfeit DS18B20 probes out there.

However, I think the location of the MAX31820 description might lead people to consider it a cloned chip.  (It doesn't state the MAX31820 is a clone, but I feel it is implied by having it following the GXCAS 18B20 and 7Q-Tek QT18B20.)  Maxim Integrated (having purchased Dallas Semiconductor) is the manufacturer of the original DS18B20.

Perhaps adding the following to the beginning of the MAX31820 description would prevent the misinterpretation:
"Maxim Integrated in addition to producing the authentic DS18B20s are producing the very similar MAX31820."

**Comment by cpetrich** [comment]
thanks for the pointer. Finally got around to it.
