### ISSUE TITLE
which providers were reliable?

### ISSUE THREAD

**Issue by jerabaul29** [cpetrich/counterfeit_DS18B20#27]
Would you be able to suggest some "reliable" providers? I see that both Sparkfun and Adafruit are listed as possible retailers. Were their sensors likely to be authentic or fakes according to your tests?

**Comment by Erriez** [comment]
I use "reliable" sensors in Europe from https://www.reichelt.nl or https://www.reichelt.de.
Most fake sensors comes from Aliexpress.

**Comment by cpetrich** [comment]
Please see issue #6.
