### ISSUE TITLE
Family C 

### ISSUE THREAD

**Issue by koendv** [cpetrich/counterfeit_DS18B20#32]
FYI. Family C seems to be Sensylink CT1820,
- 30 ms conversion time
- configuration register always 0x7f

Available at [lcsc](https://www.lcsc.com/product-detail/Temperature-Sensors_SENSYLINK-CT1820BZ_C5121991.html)

[2208100930_SENSYLINK-CT1820BZ_C5121991.pdf](https://github.com/cpetrich/counterfeit_DS18B20/files/9541720/2208100930_SENSYLINK-CT1820BZ_C5121991.pdf)
[SENSYLINK Microelectronics Co., LTD. (CT1820) Single-Wire Digital Temperature Sensor.pdf](https://github.com/cpetrich/counterfeit_DS18B20/files/9541722/SENSYLINK.Microelectronics.Co.LTD.CT1820.Single-Wire.Digital.Temperature.Sensor.pdf)

**Comment by cpetrich** [comment]
Much appreciated!!

I've suspected so much, ordered some parts to confirm but haven't gotten around to actually testing/verifying yet.
