### ISSUE TITLE
unused var

### ISSUE THREAD

**Issue by Franck78** [cpetrich/counterfeit_DS18B20#37]
https://github.com/cpetrich/counterfeit_DS18B20/blob/b6f80b3ce0baca8105715ed2b02339f00a5c8adf/classify_fake_DS18B20.ino#L312

please fix this line, remove it or use r93 at line 320.
https://github.com/cpetrich/counterfeit_DS18B20/blob/b6f80b3ce0baca8105715ed2b02339f00a5c8adf/classify_fake_DS18B20.ino#L320

But don't let compiler warnings (actually errors under arduino IDE)

Thank you

**Comment by cpetrich** [comment]
thank you. Should be fixed now as per 1478e68.
