### ISSUE TITLE
interested in high resolution die images?

### ISSUE THREAD

**Issue by JohnDMcMaster** [cpetrich/counterfeit_DS18B20#8]
If you still have the physical dies (ie through Nga P. Dang?) I'd be interested to take high resolution photos of them and post them online. Let me know if you have any interest. Thanks!

John (Santa Clara CA, USA)

**Comment by cpetrich** [comment]
John, thank you for taking note. We actually meant to image them at the local University for a bunch of reasons but have to see when the SARS-CoV-2 measures get relaxed. I'll gladly send them to you if the University still has relevant restrictions in place in September.
